In [2]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [3]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()['version'])

8.2.6

In [4]:
db = client['loja']
colecao = db['vendas']

In [5]:
dados = [
    {
        "cliente": "Ana",
        "produto": "Mouse",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 50,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 1),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Bruno",
        "produto": "Teclado",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 120,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Carla",
        "produto": "Caderno",
        "categoria": "Papelaria",
        "quantidade": 5,
        "preco_unitario": 15,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "Daniel",
        "produto": "Caneta",
        "categoria": "Papelaria",
        "quantidade": 10,
        "preco_unitario": 3,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Elaine",
        "produto": "Monitor",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 900,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Fabio",
        "produto": "Mochila",
        "categoria": "Acessórios",
        "quantidade": 2,
        "preco_unitario": 80,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Boleto"
    },
    {
        "cliente": "Gabriela",
        "produto": "Livro",
        "categoria": "Livros",
        "quantidade": 3,
        "preco_unitario": 40,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Henrique",
        "produto": "Fone",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 150,
        "cidade": "Assis",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Isabela",
        "produto": "Agenda",
        "categoria": "Papelaria",
        "quantidade": 4,
        "preco_unitario": 20,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "João",
        "produto": "Webcam",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 250,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 6),
        "forma_pagamento": "Pix"
    }
]

In [6]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69c32d5daac976e5b3940fbb'), ObjectId('69c32d5daac976e5b3940fbc'), ObjectId('69c32d5daac976e5b3940fbd'), ObjectId('69c32d5daac976e5b3940fbe'), ObjectId('69c32d5daac976e5b3940fbf'), ObjectId('69c32d5daac976e5b3940fc0'), ObjectId('69c32d5daac976e5b3940fc1'), ObjectId('69c32d5daac976e5b3940fc2'), ObjectId('69c32d5daac976e5b3940fc3'), ObjectId('69c32d5daac976e5b3940fc4')], acknowledged=True)

In [7]:
dado_exemplo = list(colecao.find({'cliente' : 'Bruno'}))
display(dado_exemplo)

[{'_id': ObjectId('69c3186c49bd9246ce54ea08'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32d5daac976e5b3940fbc'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'}]

In [8]:
dados_mongo = list(colecao.find({
    'preco_unitario' : {'$gte' : 100, '$lte' : 300}
}))

display(dados_mongo)

[{'_id': ObjectId('69c3186c49bd9246ce54ea08'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3186c49bd9246ce54ea0e'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3186c49bd9246ce54ea10'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32d5daac976e5b3940fbc'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32d5daac976e5b3940fc2'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32d5daac976e5b3940fc4'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [9]:
dados_cidade = list(colecao.find({
    'cidade' : {'$in' : ['Ourinhos', 'Assis']}
}))

display(dados_cidade)

[{'_id': ObjectId('69c3186c49bd9246ce54ea07'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3186c49bd9246ce54ea09'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3186c49bd9246ce54ea0b'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3186c49bd9246ce54ea0d'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3186c49bd9246ce54ea0e'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3186c49bd9246ce54ea10'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32d5daac976e5b3940fbb'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32d5daac976e5b3940fbd'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c32d5daac976e5b3940fbf'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32d5daac976e5b3940fc1'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32d5daac976e5b3940fc2'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32d5daac976e5b3940fc4'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [10]:
df = pd.DataFrame(dados_cidade)
df

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento
0,69c3186c49bd9246ce54ea07,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
1,69c3186c49bd9246ce54ea09,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
2,69c3186c49bd9246ce54ea0b,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
3,69c3186c49bd9246ce54ea0d,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
4,69c3186c49bd9246ce54ea0e,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
5,69c3186c49bd9246ce54ea10,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix
6,69c32d5daac976e5b3940fbb,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
7,69c32d5daac976e5b3940fbd,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
8,69c32d5daac976e5b3940fbf,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
9,69c32d5daac976e5b3940fc1,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
10,69c32d5daac976e5b3940fc2,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
11,69c32d5daac976e5b3940fc4,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix

In [11]:
df.isnull().sum()

_id                0
cliente            0
produto            0
categoria          0
quantidade         0
preco_unitario     0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [12]:
df['valor_total'] = df['quantidade' ] * df['preco_unitario'] #criou uma coluna chamada VALOR_TOTAL e calculou o total de cada compra
df.head(3)

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento,valor_total
0,69c3186c49bd9246ce54ea07,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão,100
1,69c3186c49bd9246ce54ea09,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro,75
2,69c3186c49bd9246ce54ea0b,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão,900

In [13]:
faturamento = df['valor_total'].sum() #ver o faturamento total de todos os itens
print("Faturamento Total: ",  faturamento)

Faturamento Total:  3490

In [14]:
faturamento_categoria = df.groupby('categoria')['valor_total'].sum().sort_values(ascending = False) #agrupa por CATEGORIA e vê quanto cada uma faturou; organiza do maior p/ o menor
faturamento_categoria

categoria
Informática    3100
Livros          240
Papelaria       150
Name: valor_total, dtype: int64

In [15]:
faturamento_produto = df.groupby('produto')['valor_total'].sum().sort_values(ascending = False) #agrupa por PRODUTO e vê quanto cada um faturou; organiza do maior p/ o menor
faturamento_produto

produto
Monitor    1800
Fone        600
Webcam      500
Livro       240
Mouse       200
Caderno     150
Name: valor_total, dtype: int64

In [16]:
vendas_por_cidade = df['cidade'].value_counts() #ver qts vendas tem em cada CIDADE
vendas_por_cidade

cidade
Ourinhos    10
Assis        2
Name: count, dtype: int64

In [17]:
media_valor_vendas = df['valor_total'].mean() #calcular a média das vendas
print(f"Média do valor das vendas: R${media_valor_vendas:.2f}" )

Média do valor das vendas: R$290.83

In [18]:
produto_top = df.groupby('produto')['valor_total'].sum().idxmax() #ver produto mais vendido
print("Produto mais vendido:" , produto_top)

Produto mais vendido: Monitor

In [19]:
cidade_top = df.groupby('cidade')['valor_total'].sum().idxmax() #ver cidade com mais vendas
print ("Cidade com mais vendas: ", cidade_top)

Cidade com mais vendas:  Ourinhos

In [21]:
relatorio = {
    'data_geracao' : datetime.now(),
    'faturamento_total' : float(faturamento),
    'faturamento_categoria' : faturamento_categoria.to_dict(),
    'produto_top' : produto_top,
    'cidade_top' : cidade_top 
}
display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 25, 0, 37, 28, 154357),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}

In [22]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InsertOneResult(ObjectId('69c32e6baac976e5b3940fc5'), acknowledged=True)

In [23]:
for r in colecao_relatorios.find():
    display(r)

{'_id': ObjectId('69c32e6baac976e5b3940fc5'),
 'data_geracao': datetime.datetime(2026, 3, 25, 0, 37, 28, 154000),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}